spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.hbm2ddl.auto: update
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
