springdoc:
  packages-to-scan: com.lantanagroup.link
  packages-to-exclude: org.hl7.fhir, org.hl7.fhir.r4.model
  pre-loading-enabled: true
  show-login-endpoint: true
  api-docs:
    enabled: true
    path: /api-docs
    packages-to-exclude: com.lantanagroup.link
  swagger-ui:
    disable-swagger-default-url: true
    enabled: true
    url: /api/docs
    path: /api-docs.html
    oauth2RedirectUrl: http://localhost:8082/swagger-ui/oauth2-redirect.html
swagger:
  auth-url:
  token-url:
  scope:
    - openid
    - profile
api:
  fhir-server-store:
  auth-jwks-url:
  downloader: com.lantanagroup.link.nhsn.MeasureReportDownloader
  sender: com.lantanagroup.link.nhsn.FHIRSender
  patient-id-resolver: com.lantanagroup.link.nhsn.StoredListProvider
  events:
    before-patient-data-store:
      - com.lantanagroup.link.nhsn.ApplyConceptMaps
  send-url:
  cors:
    allowed-origins: '*'
    allowed-headers: '*'
    allowed-credentials: true
    allowed-methods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
  terminology:
    covid-codes-value-set: classpath:2.16.840.1.113762.1.4.1146.1124.xml
    ventilator-codes-value-set: classpath:mechanical-ventilators.xml
    intubation-procedure-codes-value-set: classpath:intubation-procedures.xml
  document-reference-system: urn:ietf:rfc:3986
  user:
    timezone: UTC
query:
  query-class: com.lantanagroup.link.query.uscore.Query
  uscore:
    queries:
      - Encounter?patient=Patient/{{patientId}}
      - Condition?patient=Patient/{{patientId}}
      - MedicationRequest?patient=Patient/{{patientId}}
      - Observation?category=laboratory&patient=Patient/{{patientId}}
      - Procedure?patient=Patient/{{patientId}}
      - ServiceRequest?patient=Patient/{{patientId}}
      - Coverage?patient=Patient/{{patientId}}
    additional-resources:
      - Location/{{locationId}}
      - Medication/{{medicationId}}
