swagger:
  auth-url: https://thsa1.sanerproject.org:8443/realms/THSA/protocol/openid-connect/auth?nonce="1234testapi1234"
  token-url: https://thsa1.sanerproject.org:8443/realms/THSA/protocol/openid-connect/token
  scope:
    - openid
    - profile
api:
  document-reference-system: urn:ietf:rfc:3986
  patient-id-resolver: com.lantanagroup.link.nhsn.StoredListProvider
  require-https: true
  check-ip-address: false
  sender: com.lantanagroup.link.nhsn.FileSystemSender # com.lantanagroup.link.nhsn.FHIRSender
  downloader: com.lantanagroup.link.thsa.MeasureReportDownloader
  public-address: http://localhost:8080/api
  data-store:
    base-url: https://thsa1.sanerproject.org:9442/fhir # data store
    username: test-user
    password: test-password!
  auth-jwks-url: https://thsa1.sanerproject.org:8443/realms/THSA/protocol/openid-connect/certs
  algorithm: RSA256
  token-verification-class: com.lantanagroup.link.auth.OAuthTokenValidator
  issuer: https://thsa1.sanerproject.org:8443/realms/THSA
  evaluation-service: https://thsa1.sanerproject.org:9443/fhir # CQF
  terminology-service: https://thsa1.sanerproject.org:9443/fhir # CQF
  report-aggregator: com.lantanagroup.link.thsa.THSAAggregator
  Data-Processor:
    csv: com.lantanagroup.link.thsa.GenericCSVProcessor
  query:
    mode: Local
  report-defs:
    max-retry: 20
    retry-wait: 5000
    urls:
      - bundle-id: THSAMeasure
        #url: https://thsa1.sanerproject.org:9443/fhir/Measure/THSAMeasure
        url: https://ehr-test.nhsnlink.org/fhir/Bundle/THSAMeasure
        #url: http://fhir:8080/fhir/Bundle/THSAMeasure This didn't work
        report-aggregator: com.lantanagroup.link.thsa.THSAAggregator
  measure-packages:
    - bundle-ids: [ 'THSAMeasure' ]
      id:  THSAMeasure
  concept-maps:
    - local-codes-cerner-test
  cors:
    allowed-origins: '*'
    allowed-headers: '*'
    allowed-credentials: false
    allowed-methods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
thsa:
  data-measure-report-id: 2e8d4719-770a-4151-bd4f-a62b2da7f1b8 #inventorydata
sender:
  file:
    path: #/Users/moodya/Downloads
    format: JSON
    pretty: true
  fhir:
    send-urls:
      #- url: http://fhir:8080/fhir
      #- url: http://localhost:9092/fhir
      - url: https://thsa1.sanerproject.org:9441/fhir # https://thsa1.sanerproject.org/fhir
        auth-config:
          credential-mode: Password
          token-url: https://thsa1.sanerproject.org:8443/realms/THSA/protocol/openid-connect/token
          username: consumer
          password: Temp@123
          client-id: nhsnlink-app
          #thsa-api
          scope: email profile
query:
  require-https: true
  fhir-server-base: https://pmh-vmhaitst-01.pmh.org/FHIRVALPHI/api/fhir/R4
  query-class: com.lantanagroup.link.query.uscore.Query
  auth-class: com.lantanagroup.link.query.auth.EpicAuth
  auth:
    epic:
      token-url: https://pmh-vmhaitst-01.pmh.org/FHIRVALPHI/oauth2/token
      audience: https://pmh-vmhaitst-01.pmh.org/FHIRVALPHI/oauth2/token
      client-id: 6f8c6bde-3587-417c-9ef0-a435d5b13dd7
      key: 'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCNmTQi87rHLm9z
            DdPqHHb2Dm4JOLyk19KGPpjLtaqvwr6gMqjN76GVQwUeAwfLnKqpHviXVnbDnlAS
            neNGmQzJbkmBsJmlzoEtPNPI08VK6adVzRURjqEryMQKqMH33fQXcPWP78gG7+Mj
            K7XOikZQiyJe20CJ/RwqbUZsYCDeZw6CUNOULgmCDsUnOZa4tAFJ0MnzbbKO8VoV
            tQiZhfqP06byn/XxgLu4WvepRWDlyUvT2caohWrEHEn+pzNQL4ymJW5ezXRlNPoK
            1oaRauBAl3M6o2+3DMo/tzvuFFXBoeiy9dY0FM+dV1unIP1cWGRTePsHBKwkSpxP
            ljbKzExbAgMBAAECggEAAWSKiufpXR67o1euMsGTB4bgeWrbZCaTEgdK0DohRH6F
            tV1WpAvooCBF6KrwaE0DIdMMxa72+msJKOvwh9f1NGgAIaVDM9iwhgX/FblSoNny
            fcsq/rdhe3Mn6gjtApmCyCuTpsCBTFUO7dIhoX5iWas8rEC7fkcTOR/UllRqKssp
            9X6acElPRkGmxm2ZUvLQahk0NK/E6qKOfeuYGWkyvYDSNEKYLCOolQNYXHMpTeZF
            PGSEacn0bMSuVeHksRq0yux06Udyb5UxyIxMxL8XCN0bWHXDOj+Ov+R4WYyQR4MJ
            JZYbblj1eA3btAFq+HPKTHQQa3LXeoUv666E5jaS7QKBgQC+buBBSsOpu+fZU6YB
            1Gf84iH37txmEtN7U9XE9FkKiDRkOd13MgkGUZTRgqeCIotAqK6ygepmSV+DirvS
            ef2EuFnjity1z5T8Ie7+n+Dg4AJhQM2efu6Wp7F1u8c2L+ln+hmbneiwVctp+tKi
            cpkMdOz46AZ/8sZJCRxuGH3LZwKBgQC+WfOFd7zuyKyzRM+gPEvqzV6cI4KbmPxw
            JCyFomjpZaGglzcgUAbr6vY7D1pjVrSfvnjtxYNva3Mb4O5wCgpbpsjk4n4EtjRr
            n0/8MtBxujw/qhmLDcDrPwU29EWOvPMsFUVJhPZtSj2mUKEaE5uzHU4gio7INqLL
            yvIExVBS7QKBgQCjufxA5qDXG+E4bry5sf894sZFvi3r7J+61tdiIJs1fOleiomo
            Y3Jy5k1G3EhckIqdKuoYO65mBwuBsxPM4GlhZIaUJd2gyzpSlHJApQDZFn+1Udv3
            OzayfLcMfEfIhOTuKo89xkQ652ieU7IpTNHdbeIYFpUQCJEGVjkFRzVQXQKBgQCV
            NlPTguoCUCI4oK8Uz08/bt9EC/381K7FhUW1N3t/waAyD3cyCCl004lTAJT9G+GY
            +yk2UcbXF2ZzKx4di3FVKOd/rB/Wt7Fdz9NWQcrt62wBB+jf/NcGUS9YRaEk4+7G
            1qGqoOS/BRxQfBHdLBO4EzfEAHkubs2sbJjMrpNpfQKBgDFfeHTzQvXAMcgP8wJx
            m3mVKqeOqSCKhYJhEjQXQi6UFVQpeX3ty1Ljhkw+6Go/hizhU4spke4H5XjPusXM
            86jyPt7GKmVLq0UKCSojanIwWaHq0fe+jdqjoH5dKEEkUFVyZneD/0V0IbkaPnur
            GAW2rkUQ5U3J0qT4SSpJaTiW'
uscore:
  require-https: true
  fhir-server-base: https://pmh-vmhaitst-01.pmh.org/FHIRVALPHI/api/fhir/R4
  parallel-patients: 20
  patient-resource-types:
    - Encounter
    - Condition
    - Flag
    #- MedicationRequest
    #- Observation
    - Procedure
    - ServiceRequest
    #- Coverage
    #- MedicationAdministration
    #- Patient
  other-resource-types:
  #- Location
  #- Medication
consumer:
  auth-jwks-url: https://thsa1.sanerproject.org:8443/realms/THSA/protocol/openid-connect/certs
  issuer: https://thsa1.sanerproject.org:8443/realms/THSA
  permissions:
    - resourceType: Bundle
      roles:
        - name: default
          permission: [read, write]
    - resourceType: Measure
      roles:
        - name: default
          permission: [read, $report-csv]
    - resourceType: MeasureReport
      roles:
        - name: default
          permission: [read]
