swagger:
  auth-url:
  token-url:
  scope:
    - openid
    - profile
api:
  fhir-server-store:
  auth-jwks-url:
  Data-Processor:
    csv: GenericCSVProcessor
  downloader: com.lantanagroup.link.nhsn.MeasureReportDownloader
  sender: com.lantanagroup.link.nhsn.XMLSender
  patient-id-resolver: com.lantanagroup.link.nhsn.StoredListProvider
  report-aggregator: com.lantanagroup.link.thsa.THSAAggregator
  events:
    before-patient-data-store:
      - com.lantanagroup.link.nhsn.ApplyConceptMaps
      - com.lantanagroup.link.nhsn.FixResourceId
  send-url:
  delete-after-submission: true
  cors:
    allowed-origins: '*'
    allowed-headers: '*'
    allowed-credentials: true
    allowed-methods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
  document-reference-system: urn:ietf:rfc:3986
  user:
    timezone: UTC
  report-defs:
    max-retry: 5
    retry-wait: 5000
  query:
    mode: Local
thsa:
  dataMeasureReportId: inventorydata
query:
  require-https: true
  parallel-patients: 10
  query-class: com.lantanagroup.link.query.uscore.Query
  uscore:
    queries:
      - Encounter?patient=Patient/{{patientId}}
      - Condition?patient=Patient/{{patientId}}
      - MedicationRequest?patient=Patient/{{patientId}}
      - Observation?category=laboratory&patient=Patient/{{patientId}}
      - Procedure?patient=Patient/{{patientId}}
      - ServiceRequest?patient=Patient/{{patientId}}
      - Coverage?patient=Patient/{{patientId}}
    additional-resources:
      - Location/{{locationId}}
      - Medication/{{medicationId}}
