query:
  fhir-server-base: https://fhir-ehr-code.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d
  auth-class: com.lantanagroup.nandina.query.auth.CernerOAuth2
  allowed-remote:
    - 127.0.0.1
  auth:
    client-id: 317986e4-e608-4d1c-9b84-da6146790730
    secret: VStlal_dOB3LDEgG93wx0ZEPDURZWamD
    scopes: system/AllergyIntolerance.read system/Condition.read system/Observation.read system/Encounter.read system/Patient.read system/MedicationRequest.read system/Procedure.read
    token-url: https://authorization.cerner.com/tenants/ec2458f2-1e24-41c8-b71b-0e701af7583d/protocols/oauth2/profiles/smart-v1/token